name: Checker

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v3
          
       - name: Bash Validation
         shell: bash
         run: |
          files=$(find . -type f -name "*.sh")
          for file in $files; do
            echo "Validating $file"
            bash -n "$file"
            if [ $? -ne 0 ]; then
              echo "Syntax error in $file"
              exit 1
            else
              echo "$file has no syntax errors."
            fi
          done
          
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:          
       - name: MegaLinter
         uses: oxsecurity/megalinter@v8.5.0
         DISABLE:
          - CLOUDFORMATION
          - COPYPASTE
          - CSS
          - EDITORCONFIG
          - JAVASCRIPT
          - TEKTON

        
          
